// awfixer.com/src/components/ui/badge.tsx
import * as React from "react";

import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";

const badgeVariants = cva(
  "inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
  {
    variants: {
      variant: {
        default:
          "border-transparent bg-primary text-primary-foreground",
        secondary:
          "border-transparent bg-secondary text-secondary-foreground",
        destructive:
          "border-transparent bg-destructive text-destructive-foreground",
        outline: "text-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
);

function Badge({
  className,
  variant,
  ...props
}: React.ComponentProps<"div"> & VariantProps<typeof badgeVariants>) {
  return (
    <div
      data-slot="badge"
      className={cn(badgeVariants({ variant }), className)}
      {...props}
    />
  );
}

export { Badge, badgeVariants };

// awfixer.vip/src/components/ui/badge.vue
<template>
  <component
    :is="asChild ? 'slot' : 'span'"
    data-slot="badge"
    :class="cn(badgeVariants({ variant }), className)"
    v-bind="$attrs"
  >
    <slot />
  </component>
</template>

<script setup lang="ts">
import { cn } from '@/lib/utils'
import { badgeVariants } from './badge.variants'

interface Props {
  variant?: 'default' | 'secondary' | 'destructive' | 'outline'
  asChild?: boolean
  className?: string
}

withDefaults(defineProps<Props>(), {
  variant: 'default',
  asChild: false
})
</script>
